In [1]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
b  = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
print(b.shape)

(2, 3)


In [4]:
oneDimArray = np.array([10,20,30])
print(oneDimArray)
print(oneDimArray.shape)

[10 20 30]
(3,)


In [5]:
print("The dimension of b is ",b.ndim)
print("The dimension of a is ",a.ndim)
print("The data type of b is ",b.dtype)
print("The data type of a is ",a.dtype)
print("The data byte per element number for b is ",b.itemsize)
print("The data byte per element number for a is ",a.itemsize)
print("Total byte in b ",b.nbytes)
print("Total byte in a ",a.nbytes)

The dimension of b is  2
The dimension of a is  1
The data type of b is  int64
The data type of a is  int64
The data byte per element number for b is  8
The data byte per element number for a is  8
Total byte in b  48
Total byte in a  24


In [6]:
c = np.array([1,2,3], dtype = np.int8)
print(c.dtype)

int8


Indexing and slicing

In [7]:
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
print("The shape of b is ",b.shape)

The shape of b is  (2, 3)


In [9]:
print(b[1,2])

6


In [10]:
print(b[0,:])

[1 2 3]


In [11]:
print(b[:,2])

[3 6]


In [12]:
print(b)

[[1 2 3]
 [4 5 6]]


In [13]:
b[1,2]=20
print(b)

[[ 1  2  3]
 [ 4  5 20]]


In [14]:
b[:,2] = (2,9)
print(b)

[[1 2 2]
 [4 5 9]]


In [15]:
b[0,:]  = [3,2,55]
print(b)

[[ 3  2 55]
 [ 4  5  9]]


Replace one column with zeros and then replace one row with [9,9,9]

In [16]:
b[:,0] = [44,55]
b[0,:] = [9,9,9]
print(b)

[[ 9  9  9]
 [55  5  9]]


In [17]:
d = np.array([[[1,2,3],[4,5,6],[7,8,9],[3,4,7]]])
print(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [3 4 7]]]


In [18]:
print(d.shape)
print(d.ndim)
print(d.dtype)

(1, 4, 3)
3
int64


In [19]:
print(d[0,2,2])

9


In [37]:
print(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [3 4 7]]]


In [20]:
print(d[0,3,0:1:1])

[3]


In [21]:
e = np.array([[[1,2,3],[4,5,6],[6,7,8]],[[7,8,9],[3,4,7],[3,4,5]],[[4,5,6],[5,6,7],[4,5,6]]])

In [22]:
print(e)

[[[1 2 3]
  [4 5 6]
  [6 7 8]]

 [[7 8 9]
  [3 4 7]
  [3 4 5]]

 [[4 5 6]
  [5 6 7]
  [4 5 6]]]


In [23]:
print(e[2,0,2])

6


In [24]:
print(e[:,2,:])

[[6 7 8]
 [3 4 5]
 [4 5 6]]


In [25]:
e[:,2,:] = [[11,22,33],[33,44,55],[55,66,77]]
print(e)

[[[ 1  2  3]
  [ 4  5  6]
  [11 22 33]]

 [[ 7  8  9]
  [ 3  4  7]
  [33 44 55]]

 [[ 4  5  6]
  [ 5  6  7]
  [55 66 77]]]


In [26]:
print(e[:,:,2])

[[ 3  6 33]
 [ 9  7 55]
 [ 6  7 77]]


In [27]:
e[:,:,2] = [[33,44,55],[22,3,55],[88,55,33]]
print(e)

[[[ 1  2 33]
  [ 4  5 44]
  [11 22 55]]

 [[ 7  8 22]
  [ 3  4  3]
  [33 44 55]]

 [[ 4  5 88]
  [ 5  6 55]
  [55 66 33]]]


Creating Special Array

In [28]:
f = np.zeros((3,3))
print(f)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
f = np.ones((3,5,3))
print(f)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [30]:
g = np.full((2,2),([6,9],[4,5]))
print(g)

[[6 9]
 [4 5]]


In [31]:
h = np.eye(3,3,4)
print(h)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
i = np.random.randint(0,10,size=(3,3))
print(i)

[[9 9 8]
 [3 3 9]
 [8 9 5]]


In [33]:
j = np.random.rand(3,3,4)
print(j)

[[[0.24674594 0.60098132 0.17229738 0.75899789]
  [0.72010344 0.39250196 0.87277767 0.1501608 ]
  [0.64739367 0.27042467 0.66819173 0.2695501 ]]

 [[0.07210003 0.76845573 0.55028854 0.36165785]
  [0.03366083 0.92550374 0.42031891 0.21689515]
  [0.36528259 0.05913518 0.47607979 0.60955307]]

 [[0.10308925 0.48656941 0.16902681 0.15820623]
  [0.4917617  0.10072135 0.80406768 0.34456359]
  [0.5632981  0.93665274 0.05693763 0.86008169]]]


In [34]:
print(b)

[[ 9  9  9]
 [55  5  9]]


In [35]:

print(b + 2)

[[11 11 11]
 [57  7 11]]


In [36]:
k = np.sin(b)
print(k)

[[ 0.41211849  0.41211849  0.41211849]
 [-0.99975517 -0.95892427  0.41211849]]


In [38]:
print(a)

[1 2 3]


In [40]:
new_mat = np.random.randint(0,10,size=(4,3))
print(new_mat)

[[8 9 2]
 [4 4 8]
 [8 5 3]
 [6 3 2]]


In [42]:
second_mat = np.random.randint(0,10,size=(3,5))
print(second_mat)

[[3 6 3 5 7]
 [9 7 3 0 3]
 [2 4 6 9 6]]


In [45]:
print(np.matmul(new_mat, second_mat).shape)

(4, 5)


In [48]:
square_matrix = np.random.randint(0,10,size=(3,3))
print(square_matrix)

[[6 5 6]
 [9 7 7]
 [2 1 2]]


In [49]:
print(np.linalg.det(square_matrix))

-8.000000000000005


In [54]:
n = np.ones((3,4))
print(n)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [81]:
# print(a)
print(i)
new_mat = np.hstack([i,square_matrix])
print(new_mat)

[[9 9 8]
 [3 3 9]
 [8 9 5]]
[[9 9 8 6 5 6]
 [3 3 9 9 7 7]
 [8 9 5 2 1 2]]


In [69]:
n1 = n.reshape((6,2))
# print(n1)
print(f.shape)

print(f)
f1 = f.reshape(3,3,5)
print(f1)

(3, 5, 3)
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [95]:
newVector = np.arange(3)
print(newVector)
newMatrix = np.random.randint(1,9,size=(3,3))
print(newMatrix)

newVecMat = np.reshape(newVector,(1,3))
print(newVecMat)
newMatVec = np.reshape(newMatrix,(9,))
print(newMatVec)

[0 1 2]
[[8 6 5]
 [7 4 6]
 [3 6 7]]
[[0 1 2]]
[8 6 5 7 4 6 3 6 7]


In [102]:
new_rand_arr = np.random.randint(1,9,size=(4,5))
print(new_rand_arr)
print("The shape of the matrix is",new_rand_arr.shape)

#normal slicing
print(new_rand_arr[1:3,0:4:2])

[[2 1 2 4 5]
 [7 2 1 5 6]
 [8 4 6 7 5]
 [1 6 4 8 5]]
The shape of the matrix is (4, 5)
[[7 1]
 [8 6]]


In [104]:
print(new_rand_arr[[0,2,1]])

[[2 1 2 4 5]
 [8 4 6 7 5]
 [7 2 1 5 6]]


In [105]:
print(new_rand_arr[[0,3,1],[3,2,0]])

[4 4 7]


In [111]:
print(new_rand_arr[[3,2,1],1:4:3])
print(new_rand_arr[:,1:4:3])

[[6]
 [4]
 [2]]
[[1]
 [2]
 [4]
 [6]]
